export const LOADING = "LOADING";
export const AUTH_LOADING = "AUTH_LOADING";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_INITIAL_AUTH = "SET_INITIAL_AUTH";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_ERROR = "USER_RESET_PASSWORD_ERROR";

//Show Loader
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";

//Expense
export const EXPENSE_LOADING = "EXPENSE_LOADING";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const EXPENSE_LIST_SUCCESS = "EXPENSE_LIST_SUCCESS";
export const SET_INITIAL_EXPENSE = "SET_INITIAL_EXPENSE";
export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS";
export const EXPENSE_ERROR = "EXPENSE_ERROR";

//Leave
export const CREATE_LEAVE_QUOTA_SUCCESS = "CREATE_LEAVE_QUOTA_SUCCESS";
export const LEAVE_QUOTA_LIST_SUCCESS = "LEAVE_QUOTA_LIST_SUCCESS";
export const UPDATE_LEAVE_REQUEST_SUCCESS = "UPDATE_LEAVE_REQUEST_SUCCESS";
export const CREATE_LEAVE_REQUEST_SUCCESS = "CREATE_LEAVE_REQUEST_SUCCESS";
export const LEAVE_REQUESTS_LIST_SUCCESS = "LEAVE_REQUESTS_LIST_SUCCESS";
export const HOLIDAYS_LIST_SUCCESS = "HOLIDAYS_LIST_SUCCESS";
export const CREATE_HOLIDAYS_SUCCESS = "CREATE_HOLIDAYS_SUCCESS";
export const DELETE_HOLIDAYS_SUCCESS = "DELETE_HOLIDAYS_SUCCESS";
export const LEAVE_TYPE_SUCCESS = "LEAVE_TYPE_SUCCESS";
export const SET_INITIAL_LEAVE = "SET_INITIAL_LEAVE";
export const LEAVE_LIST_SUCCESS = "LEAVE_LIST_SUCCESS";
export const LEAVE_LOADING = "LEAVE_LOADING";
export const LEAVE_SUCCESS = "LEAVE_SUCCESS";
export const LEAVE_ERROR = "LEAVE_ERROR";

//Organization
export const ORGANIZATION_API_LOADING = "ORGANIZATION_API_LOADING";
export const DESIGNATION_LIST_SUCCESS = "DESIGNATION_LIST_SUCCESS";
export const DESIGNATION_UPDATE_SUCCESS = "DESIGNATION_UPDATE_SUCCESS";
export const DESIGNATION_DELETE_SUCCESS = "DESIGNATION_DELETE_SUCCESS";
export const ORGANIZATION_API_ERROR = "ORGANIZATION_API_ERROR";
export const ORGANIZATION_EXPENSE_LIST_SUCCESS =
  "ORGANIZATION_EXPENSE_LIST_SUCCESS";
export const CREATE_DESIGNATION_SUCCESS = "CREATE_DESIGNATION_SUCCESS";
export const CREATE_ASSET_SUCCESS = "CREATE_ASSET_SUCCESS";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const ASSET_LIST_SUCCESS = "ASSET_LIST_SUCCESS";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const SET_INITIAL_ORGANIZATION = "SET_INITIAL_ORGANIZATION";
export const EMPLOYEE_PROFILE_SUCCESS = "EMPLOYEE_PROFILE_SUCCESS";

//Timesheet & Attendance
export const TIMELOGS_LOADING = "TIMELOGS_LOADING";
export const TIMELOGS_TODAY_SUCCESS = "TIMELOGS_TODAY_SUCCESS";
export const TIMELOGS_WEEK_SUCCESS = "TIMELOGS_WEEK_SUCCESS";
export const TIMELOGS_MONTH_SUCCESS = "TIMELOGS_MONTH_SUCCESS";
export const TIMELOGS_ERROR = "TIMELOGS_ERROR";

export const CHECK_IN_LOADING = "CHECK_IN_LOADING";
export const CHECK_IN_SUCCESS = "CHECK_IN_SUCCESS";
export const CHECK_IN_ERROR = "CHECK_IN_ERROR";
export const CHECK_OUT_LOADING = "CHECK_OUT_LOADING";
export const CHECK_OUT_SUCCESS = "CHECK_OUT_SUCCESS";
export const CHECK_OUT_ERROR = "CHECK_OUT_ERROR";

export const GET_HOURS_LOADING = "GET_HOURS_LOADING";
export const GET_HOURS_SUCCESS = "GET_HOURS_SUCCESS";
export const GET_HOURS_ERROR = "GET_HOURS_ERROR";
export const UPDATE_HOURS_LOADING = "UPDATE_HOURS_LOADING";
export const UPDATE_HOURS_SUCCESS = "UPDATE_HOURS_SUCCESS";
export const UPDATE_HOURS_ERROR = "UPDATE_HOURS_ERROR";

export const ATTENDANCE_LOADING = "ATTENDANCE_LOADING";
export const USERS_ATTENDANCE_SUCCESS = "USERS_ATTENDANCE_SUCCESS";
export const ATTENDANCE_ERROR = "ATTENDANCE_ERROR";

export const EMPLOYEE_LIST_TIMELOGS_SUCCESS = "EMPLOYEE_LIST_TIMELOGS_SUCCESS";
export const EMPLOYEE_CREATE_TIMELOGS_SUCCESS =
  "EMPLOYEE_CREATE_TIMELOGS_SUCCESS";
export const EMPLOYEE_UPDATE_TIMELOGS_SUCCESS =
  "EMPLOYEE_UPDATE_TIMELOGS_SUCCESS";
export const EMPLOYEE_UPDATE_HOURS_SUCCESS = "EMPLOYEE_UPDATE_HOURS_SUCCESS";
export const EMPLOYEE_DELETE_TIMELOG_SUCCESS =
  "EMPLOYEE_DELETE_TIMELOG_SUCCESS";

//Projects
export const PROJECT_LOADING = "PROJECT_LOADING";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CLIENTS_LIST_SUCCESS = "CLIENTS_LIST_SUCCESS";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const CLIENT_DETAIL_SUCCESS = "CLIENT_DETAIL_SUCCESS";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const PROJECTS_LIST_SUCCESS = "PROJECTS_LIST_SUCCESS";
export const CREATE_REQUIREMENT_SUCCESS = "CREATE_REQUIREMENT_SUCCESS";
export const REQUIREMENT_REQUEST_LIST_SUCCESS =
  "REQUIREMENT_REQUEST_LIST_SUCCESS";
export const GET_REQUIREMENT_REQUEST_SUCCESS =
  "GET_REQUIREMENT_REQUEST_SUCCESS";
export const UPDATE_REQUIREMENT_SUCCESS = "UPDATE_REQUIREMENT_SUCCESS";
export const PROJECT_SHOW_SUCCESS = "PROJECT_SHOW_SUCCESS";
export const PROJECT_ERROR = "PROJECT_ERROR";

//Procurement
export const PROCUREMENT_LOADING = "PROCUREMENT_LOADING";
export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
export const VENDOR_RFQ_LIST_SUCCESS = "VENDOR_RFQ_LIST_SUCCESS";
export const PROCUREMENT_ERROR = "PROCUREMENT_ERROR";
export const LIST_INTENT_SUCCESS = "LIST_INTENT_SUCCESS";
export const VENDOR_LIST_ITEMS_SUCCESS = "VENDOR_LIST_ITEMS_SUCCESS";
export const PROCUREMENT_REQUIREMENT_BY_ID_SUCCESS =
  "PROCUREMENT_REQUIREMENT_BY_ID_SUCCESS";
export const PROCUREMENT_REQUIREMENT_BY_PROJECT_ID_SUCCESS =
  "PROCUREMENT_REQUIREMENT_BY_PROJECT_ID_SUCCESS";
export const UPDATE_PROCUREMENT_REQUIREMENT_SUCCESS =
  "UPDATE_PROCUREMENT_REQUIREMENT_SUCCESS";
export const VENDOR_SHOW_SUCCESS = "VENDOR_SHOW_SUCCESS";
export const VENDORS_LIST_SUCCESS = "VENDORS_LIST_SUCCESS";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_INTENT_TO_BID = "UPDATE_INTENT_TO_BID";
export const CRATE_PURCHASE_ORDER_SUCCESS = "CRATE_PURCHASE_ORDER_SUCCESS";
export const GET_INTENT_SUCCESS = "GET_INTENT_SUCCESS";
export const PROCUREMENT_REQUIREMENT_SUCCESS =
  "PROCUREMENT_REQUIREMENT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const DOES_VENDOR_EXIST = "DOES_VENDOR_EXIST";
export const VENDOR_LOGIN_SUCCESS = "VENDOR_LOGIN_SUCCESS";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";

export const CREATE_RFQ_SUCCESS = "CREATE_RFQ_SUCCESS";
export const RFQ_LIST_SUCCESS = "RFQ_LIST_SUCCESS";
export const RFQ_BY_ID_SUCCESS = "RFQ_BY_ID_SUCCESS";
export const RFQ_BY_PROJECT_SUCCESS = "RFQ_BY_PROJECT_SUCCESS";
export const UPDATE_RFQ_SUCCESS = "UPDATE_RFQ_SUCCESS";
export const CLOSE_RFQ_SUCCESS = "RFQ_CLOSE_SUCCESS";

export const WANT_TO_BID = "WANT_TO_BID";
export const VENDOR_BID_ITEMS_SUCCESS = "VENDOR_BID_ITEMS_SUCCESS";
export const ADD_BID_ITEM_SUCCESS = "ADD_BID_ITEM_SUCCESS";
export const REMOVE_BID_ITEM_SUCCESS = "REMOVE_BID_ITEM_SUCCESS";
export const UPDATE_INTENT_SUCCESS = "UPDATE_INTENT_SUCCESS";

// Estimation
export const ESTIMATION_LOADING = "ESTIMATION_LOADING";
export const CREATE_BOQ_SUCCESS = "CREATE_BOQ_SUCCESS";
export const UPDATE_BILL_TABLE_ACTION = "UPDATE_BILL_TABLE_ACTION";
export const BOQ_LIST_SUCCESS = "BOQ_LIST_SUCCESS";
export const BOQ_BY_ID_SUCCESS = "BOQ_BY_ID_SUCCESS";
export const UPDATE_BOQ_SUCCESS = "UPDATE_BOQ_SUCCESS";
export const CREATE_PROCURE_SUCCESS = "CREATE_PROCURE_SUCCESS";
export const ESTIMATION_ERROR = "ESTIMATION_ERROR";

//Payroll
export const PAYROLL_LOADING = "PAYROLL_LOADING";
export const ALL_USERS_PAYROLL_MONTHLY_SUCCESS =
  "ALL_USERS_PAYROLL_MONTHLY_SUCCESS";
export const PAYROLL_MONTHLY_SUCCESS = "PAYROLL_MONTHLY_SUCCESS";
export const PAYROLL_DAILY_SUCCESS = "PAYROLL_DAILY_SUCCESS";
export const PAYROLL_ERROR = "PAYROLL_ERROR";

export const ASSIGN_USER_LOADING = "ASSIGN_USER_LOADING";
export const ASSIGN_USER_SUCCESS = "ASSIGN_USER_SUCCESS";
export const ASSIGN_USER_ERROR = "ASSIGN_USER_ERROR";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const SAVE_NEW_PASSWORD_SUCCESS = "SAVE_NEW_PASSWORD_SUCCESS";
export const SAVE_NEW_PASSWORD_ERROR = "SAVE_NEW_PASSWORD_ERROR";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const REGISTER_STEP2_SUCCESS = "REGISTER_STEP2_SUCCESS";
export const REGISTER_STEP2_ERROR = "REGISTER_STEP2_ERROR";

export const REGISTER_OTP_LOADING = "REGISTER_OTP_LOADING";
export const REGISTER_OTP_SUCCESS = "REGISTER_OTP_SUCCESS";
export const REGISTER_OTP_ERROR = "REGISTER_OTP_ERROR";

export const RESEND_OTP_LOADING = "RESEND_OTP_LOADING";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_ERROR = "RESEND_OTP_ERROR";

export const CRAETE_SHIFT_LOADING = "CRAETE_SHIFT_LOADING";
export const CRAETE_SHIFT_SUCCESS = "CRAETE_SHIFT_SUCCESS";
export const CRAETE_SHIFT_ERROR = "CRAETE_SHIFT_ERROR";

export const COMPANY_PROFILE_LOADING = "COMPANY_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const CRAETE_BRANCH_SUCCESS = "CRAETE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const COMPANY_PROFILE_ERROR = "COMPANY_PROFILE_ERROR";

//Subscription
export const SUBSCRIPTION_LOADING = "SUBSCRIPTION_LOADING";
export const SUBSCRIPTION_LIST_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const CANCEL_RENEWAL_SUCCESS = "CANCEL_RENEWAL_SUCCESS";
export const PREMIUM_SUBSCRIPTION_SUCCESS = "PREMIUM_SUBSCRIPTION_SUCCESS";
export const REMOVE_CARD_SUCCESS = "REMOVE_CARD_SUCCESS";
export const BILLING_HISTORY_SUCCESS = "BILLLING_HISTORY_SUCCESS";
export const BILLING_INFO_SUCCESS = "BILLING_INFO_SUCCESS";
export const BILLING_DETAIL_SUCCESS = "BILLING_DETAIL_SUCCESS";
export const PAY_BY_CARD_SUCCESS = "PAY_BY_CARD_SUCCESS";
export const PAY_BY_CARD_ERROR = "PAY_BY_CARD_ERROR";
export const SAVE_DETAIL_SUCCESS = "SAVE_DETAIL_SUCCESS";
export const SAVE_DETAIL_ERROR = "SAVE_DETAIL_ERROR";
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const CREATE_CARD_ERROR = "CREATE_CARD_ERROR";
export const SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR";
export const CLEAR_SUBSCRIPTION_DATA = "CLEAR_SUBSCRIPTION_DATA";

//Members
export const MEMBER_LOADING = "MEMBER_LOADING";
export const MEMBER_ERROR = "MEMBER_ERROR";
export const LIST_JOB_POISTIONS_SUCCESS = "LIST_JOB_POISTIONS_SUCCESS";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const DETAIL_MEMBER_SUCCESS = "DETAIL_MEMBER_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const REMOVE_MEMBER_SUCCESS = "REMOVE_MEMBER_SUCCESS";
export const LIST_MEMBER_SUCCESS = "LIST_MEMBER_SUCCESS";
export const CONNECTED_DEVICE_LIST_SUCCESS = "CONNECTED_DEVICE_LIST_SUCCESS";
export const UPDATE_ADDITIONAL_VERIFY_SUCCESS =
  "UPDATE_ADDITIONAL_VERIFY_SUCCESS";

export const COMMON_API_LOADING = "COMMON_API_LOADING";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const DOWNLOAD_IMAGE_SUCCESS = "DOWNLOAD_IMAGE_SUCCESS";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const JOB_ROLE_SUCCESS = "JOB_ROLE_SUCCESS";
export const CERTIFICATES_SUCCESS = "CERTIFICATES_SUCCESS";
export const SKILL_SUCCESS = "SKILL_SUCCESS";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const COMMON_API_ERROR = "COMMON_API_ERROR";

export const COMMON_SHIFT_API_LOADING = "COMMON_SHIFT_API_LOADING";
export const OPEN_SHIFT_SUCCESS = "OPEN_SHIFT_SUCCESS";
export const START_SHIFT_SUCCESS = "START_SHIFT_SUCCESS";
export const END_SHIFT_SUCCESS = "END_SHIFT_SUCCESS";
export const CALENDAR_SHIFT_SUCCESS = "CALENDAR_SHIFT_SUCCESS";
export const OPEN_OFFERS_SUCCESS = "OPEN_OFFERS_SUCCESS";
export const BOOKED_SHIFT_SUCCESS = "BOOKED_SHIFT_SUCCESS";
export const LOCUM_LIST_SUCCESS = "LOCUM_LIST_SUCCESS";
export const CANCELLED_SHIFTS_SUCCESS = "CANCELLED_SHIFTS_SUCCESS";
export const COMPLETED_SHIFTS_SUCCESS = "COMPLETED_SHIFTS_SUCCESS";
export const VIEW_NEGOTIATION_SUCCESS = "VIEW_NEGOTIATION_SUCCESS";
export const LOCUM_MARKET_PROFILE_SUCCESS = "LOCUM_MARKET_PROFILE_SUCCESS";
export const LOCUM_MARKET_SUCCESS = "LOCUM_MARKET_SUCCESS";
export const OFFER_PENDING_SUCCESS = "OFFER_PENDING_SUCCESS";
export const APPLICANTS_LIST_SUCCESS = "APPLICANTS_LIST_SUCCESS";
export const CONNECTED_DEVICE_SUCCESS = "CONNECTED_DEVICE_SUCCESS";
export const SHIFT_DATE_DELETE_SUCCESS = "SHIFT_DATE_DELETE_SUCCESS";
export const RELEASE_PAYMENT_SUCCESS = "RELEASE_PAYMENT_SUCCESS";
export const COMMON_SHIFT_API_ERROR = "COMMON_SHIFT_API_ERROR";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const BILLING_INFO_DETAILS_SUCCESS = "BILLING_INFO_DETAILS_SUCCESS";

export const SHIFT_DELETE_LOADING = "SHIFT_DELETE_LOADING";
export const SHIFT_DELETE_SUCCESS = "SHIFT_DELETE_SUCCESS";
export const SHIFT_DELETE_ERROR = "SHIFT_DELETE_ERROR";

export const SHIFT_CANCEL_LOADING = "SHIFT_CANCEL_LOADING";
export const SHIFT_CANCEL_ERROR = "SHIFT_CANCEL_ERROR";
export const SHIFT_CANCEL_SUCCESS = "SHIFT_CANCEL_SUCCESS";

export const ACCEPT_NEGOTIATION_LOADING = "ACCEPT_NEGOTIATION_LOADING";
export const ACCEPT_NEGOTIATION_ERROR = "ACCEPT_NEGOTIATION_ERROR";
export const ACCEPT_NEGOTIATION_SUCCESS = "ACCEPT_NEGOTIATION_SUCCESS";

export const REJECT_NEGOTIATION_LOADING = "REJECT_NEGOTIATION_LOADING";
export const REJECT_NEGOTIATION_ERROR = "REJECT_NEGOTIATION_ERROR";
export const REJECT_NEGOTIATION_SUCCESS = "REJECT_NEGOTIATION_SUCCESS";

export const APPLY_NEGOTIATION_LOADING = "APPLY_NEGOTIATION_LOADING";
export const APPLY_NEGOTIATION_ERROR = "APPLY_NEGOTIATION_ERROR";
export const APPLY_NEGOTIATION_SUCCESS = "APPLY_NEGOTIATION_SUCCESS";

export const ACCOUNT_DEACTIVATE_LOADING = "ACCOUNT_DEACTIVATE_LOADING";
export const ACCOUNT_DEACTIVATE_ERROR = "ACCOUNT_DEACTIVATE_ERROR";
export const ACCOUNT_DEACTIVATE_SUCCESS = "ACCOUNT_DEACTIVATE_SUCCESS";

export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS";

// export const APPLICANTS_LIST_SUCCESS = "APPLICANTS_LIST_SUCCESS";

// export const APPLICANTS_LIST_SUCCESS = "APPLICANTS_LIST_SUCCESS";

//Analytics
export const ANALYTICS_LEFT_SUCCESS = "ANALYTICS_LEFT_SUCCESS";
export const ANALYTICS_RIGHT_SUCCESS = "ANALYTICS_RIGHT_SUCCESS";
export const ANALYTICS_MONTHLY_SUCCESS = "ANALYTICS_MONTHLY_SUCCESS";
export const ANALYTICS_LOCUM_LIST_SUCCESS = "ANALYTICS_LOCUM_LIST_SUCCESS";
export const PAYMENT_HISTORY_LIST_SUCCESS = "PAYMENT_HISTORY_LIST_SUCCESS";

export const RESPONSE_LOADING = "RESPONSE_LOADING";
export const RESPONSE_SUCCESS = "RESPONSE_SUCCESS";
export const RESPONSE_ERROR = "RESPONSE_ERROR";
